language: php
php:
  - 7.2

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update && composer --version #travis is bad at updating composer
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
  - composer install

script:
  - vendor/bin/phpunit --bootstrap vendor/autoload.php --no-configuration ./tests
